apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
  namespace: boardgame
spec:
  selector:
    matchLabels:
      app: boardgame
  replicas: 2
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      automountServiceAccountToken: false
      containers:
        - name: boardgame
          image: "aayodeji/boardgame:IMAGE_TAG"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"  
              cpu: "250m"       
              ephemeral-storage: "500Mi" 
            limits:
              memory: "512Mi"  
              cpu: "500m"       
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: boardgame-svc
  namespace: boardgame
spec:
  selector:
    app: boardgame
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer
